"""Corpus adapter — the 71-paper canon cell list, enumerated from data.

Provenance (verified 2026-09-20, this branch):
  * Bundled snapshot: flux_verifier/corpus/canon_71.json, extracted from
    SuperInstance/quilt-live-canon @ canon-71-full-corpus, commit 371e07d
    ("canon drift closure: bundle full 71-paper committed corpus; live state
    now EQUALS canon_target"). In that tree the corpus is the CANON object
    bundled in worker.js; its data.json convention (see quilt-live-canon-pypi
    live_canon/_data.json) is {"canon": {...}, "bodies": {...}} — the
    bundled file IS the canon dict from that shape.
  * Live invariant: FNV-1a 64 over the canonical serialization of the sorted
    cell list == 0x445185a3a99fd2e7 (CANON_TARGET), guarded in the source
    repo by test/canon-hash.test.mjs.

Cell construction (byte-exact with the Worker's stateHash):
  * dials  = cell_to_dials(paper)   — port of worker.js cellToDials()
  * id     = paper["number"]
  * neighbors = paper["ref_papers"] ONLY (ref_f_numbers feed the dial count,
    not the neighbor list — worker.js stateHash maps ref_papers)
  * sort cells by id ascending, concatenate serialize_cell() of each

Ports, not re-designs: cell_to_dials mirrors worker.js cellToDials and the
quilt-live-canon-pypi cell_to_dials. JS DataView.setInt16 wraps out-of-range
dial values mod 2^16 (e.g. num_q for papers 408..478 exceeds int16); the
canonical serializer's int(d) & 0xFFFF produces the identical bytes.
"""
from __future__ import annotations

import json
import os
import re

from ..canon_serializer import serialize_cell

CANON_TARGET = 0x445185A3A99FD2E7

CORPUS_REPO = "SuperInstance/quilt-live-canon"
CORPUS_BRANCH = "canon-71-full-corpus"
CORPUS_COMMIT = "371e07d8addf850246f05c7b508a3eaa95d2dc69"
CORPUS_PAPERS = 71

_SNAPSHOT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                         "canon_71.json")

# One corpus entry per line, machine-generated by the source repo — the
# line-anchored pattern is exact and cannot be fooled by ':' inside titles.
_ENTRY_RE = re.compile(
    r'^\s*(\d+): \{\s*number: (\d+),\s*'
    r'title: "((?:[^"\\]|\\.)*)",\s*'
    r'f_number: (\d+),\s*phase: (\d+),\s*date: "([^"]*)",\s*'
    r'ref_papers: \[([^\]]*)\],\s*ref_f_numbers: \[([^\]]*)\]\s*\},?\s*$')


def parse_worker_canon(worker_js: str) -> dict[str, dict]:
    """Extract the bundled CANON corpus from quilt-live-canon worker.js.

    Returns the data.json canon shape: {str(number): paper-dict}. Raises
    ValueError when the CANON block or any entry does not match the shape
    this adapter was verified against — parse failure is data, not None.
    """
    start = worker_js.index("const CANON")
    brace = worker_js.index("{", start)
    depth = 0
    for k in range(brace, len(worker_js)):
        if worker_js[k] == "{":
            depth += 1
        elif worker_js[k] == "}":
            depth -= 1
            if depth == 0:
                block = worker_js[brace:k + 1]
                break
    else:
        raise ValueError("CANON block: no closing brace")
    canon: dict[str, dict] = {}
    for line in block.splitlines():
        m = _ENTRY_RE.match(line)
        if not line.strip() or line.strip() == "{":
            continue
        if not m:
            if line.strip().startswith("};") or line.strip() == "}":
                continue
            raise ValueError(f"CANON entry does not match verified shape: {line[:80]!r}")
        key, number, title, f_number, phase, date, refs, f_refs = m.groups()
        canon[key] = {
            "number": int(number),
            "title": title.encode("utf-8").decode("unicode_escape")
                if "\\" in title else title,
            "f_number": int(f_number),
            "phase": int(phase),
            "date": date,
            "ref_papers": [int(x) for x in refs.split(",") if x.strip()],
            "ref_f_numbers": [int(x) for x in f_refs.split(",") if x.strip()],
        }
    return canon


def load_corpus(path: str | None = None) -> dict[str, dict]:
    """The bundled 71-paper corpus ({str(number): paper-dict}, data.json shape)."""
    with open(path or _SNAPSHOT, encoding="utf-8") as fh:
        canon = json.load(fh)
    if len(canon) != CORPUS_PAPERS:
        raise ValueError(f"corpus has {len(canon)} papers, expected {CORPUS_PAPERS}")
    return canon


def cell_to_dials(paper: dict) -> list[int]:
    """worker.js cellToDials, ported. Values may exceed int16 (JS wraps mod
    2^16 at setInt16 time); serialize_cell's & 0xFFFF reproduces the bytes."""
    date = str(paper.get("date") or "1970")[:4]
    try:
        year = int(date)
    except ValueError:
        year = 1970
    year_q = (year - 1970) * 546
    phase_q = int(paper.get("phase", 0)) * 218
    f_q = int(paper.get("f_number", 0)) * 218
    n_refs = len(paper.get("ref_papers") or []) + len(paper.get("ref_f_numbers") or [])
    n_refs_q = min(0x7FFF, n_refs * 256)
    th = fnv1a_64_str(paper.get("title", ""))
    title_lo = th & 0xFFFF
    title_hi = (th >> 16) & 0xFFFF
    num = min(int(paper.get("number", 0)), 500)
    num_q = num * 131
    return [num_q, title_lo, f_q, phase_q, year_q, n_refs_q, title_hi, 0,
            0, 0, 0, 0, 0, 0, 0, 0]


def fnv1a_64_str(s: str) -> int:
    """FNV-1a 64-bit over UTF-8 (worker fnv1a_64 over TextEncoder bytes)."""
    h = 0xCBF29CE484222325
    for byte in s.encode("utf-8"):
        h ^= byte
        h = (h * 0x00000100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def corpus_cells(canon: dict[str, dict] | None = None
                 ) -> list[tuple[int, list[int], list[int]]]:
    """The fabric cell list: (id, dials, neighbors) sorted by id ascending.

    neighbors = ref_papers only — worker.js stateHash: p.ref_papers.map(Number).
    """
    canon = canon or load_corpus()
    cells = [
        (int(p["number"]), cell_to_dials(p), [int(r) for r in p.get("ref_papers") or []])
        for p in canon.values()
    ]
    cells.sort(key=lambda c: c[0])
    return cells


def fabric_bytes(canon: dict[str, dict] | None = None) -> bytes:
    """The canonical fabric serialization: concat of serialize_cell over the
    sorted cell list. FNV-1a 64 of this == CANON_TARGET by construction."""
    return b"".join(serialize_cell(cid, dials, nb)
                    for cid, dials, nb in corpus_cells(canon))
